### ISSUE TITLE
Boa Tarde, a gente está fazendo o trabalho de graduação

### ISSUE THREAD

**Issue by 09101999** [alefduarte/knapsack-problem#1]
E queremos saber se podemos utilizar o seu código, iremos referenciar que foi feito por você, mas precisamos de uma licença sua, dizendo que autoriza utilizarmos.

**Comment by 09101999** [comment]
e só para trabalho acadêmico, para conseguirmos concluir o trabalho. estamos sem tempo

**Comment by alefduarte** [comment]
Boa tarde,
Podem usar sim, vocês têm toda minha permissão para usarem este código.
Fico alegre em saber que meu código poderá ajudar vocês, espero que ele funcione da forma que precisam.
Quaisquer dúvidas estou à disposição, na medida do possível :D
